### ISSUE TITLE
Add Hub name and firmware version to iframe interface

### ISSUE THREAD

**Issue by edanahy** [tuftsceeo/Coding-Rooms-for-LEGO-Hardware#12]
Currently have battery level (good), but include Hub Name and firmware version as well.

**Comment by jeremy-jung** [comment]
I found the changed UJSONRPC script for get_firmware_info. However, Serial API at the moment does not have a function for getting port information that is implemented in Chrome/Chromium browsers. WICG's specs for Web Serial API is a little different from what is implemented. I will revisit the Hub Name issue when I find an alternative solution.

https://github.com/chromium/chromium/blob/84.0.4112.1/third_party/blink/renderer/modules/serial/serial_port.h#L46-L56

**Comment by jeremy-jung** [comment]
Added hub name! I will close this issue now.

![Screen Shot 2020-09-06 at 2 34 48 PM](https://user-images.githubusercontent.com/44676944/92318952-34aba180-f04e-11ea-86de-d03c510c4e0c.png)
