### ISSUE TITLE
Tooltips for the various interface buttons

### ISSUE THREAD

**Issue by edanahy** [tuftsceeo/Coding-Rooms-for-LEGO-Hardware#19]
Can we create some tooltips for the different buttons in the iframe?

Here is some CSS for making nice Tooltips: https://www.w3schools.com/css/css_tooltip.asp

Buttons:
- "Refresh Page" (the button in top left that refreshes iframe)
- "Connect to SPIKE Prime"
- "Coding Help"
- "Run Program" (note: the SPIKE App uses the word "Play" here)
- "Stop Program" (note: the SPIKE App uses the word "Stop" here)
- "Reboot SPIKE Prime"

Note: the SPIKE App also calls it "Select storage position" instead of "Slots" (I think they are called slots internally in the file system on the brick).  We should probably try and be consistent with the SPIKE App/LEGO protocols.

**Comment by edanahy** [comment]
This is good.  I like the tooltips.  Can you make them "appear" a bit faster (it is like almost 2-seconds it takes for them to appear, and I didn't even know they had been added because I moved too fast).  Maybe 0.5 seconds after hovering?

**Comment by jeremy-jung** [comment]
Sure! I did it for when the users are well enough accustomed to the UI that they would prefer to rather not have the tooltip come up, but I overcompensated. They're 0.5 seconds now.
