### ISSUE TITLE
"Fatal Error" error in normal program with lots of comments(?)

### ISSUE THREAD

**Issue by edanahy** [tuftsceeo/Coding-Rooms-for-LEGO-Hardware#25]
I get a Fatal Error from the SPIKE Prime when using the following program.  I can't figure out what about it is "triggering" the error, but it's something to do with the comment (deleting some lines makes it work, adding them back gives the error).

`# MicroPython for LEGO Hardware (LEGO Education's SPIKE Prime)
from spike import PrimeHub, LightMatrix, Button, StatusLight, ForceSensor, MotionSensor, Speaker, ColorSensor, App, DistanceSensor, Motor, MotorPair
from spike.control import wait_for_seconds, wait_until, Timer

hub = PrimeHub()

hub.light_matrix.show_image('HAPPY')

\# Your previous micropython-for-lego code is preserved below
\# # MicroPython for LEGO Hardware (LEGO Education's SPIKE Prime)
\# from spike.control import wait_for_seconds, wait_until, Timer
\# from spike import PrimeHub, LightMatrix, Button, StatusLight, ForceSensor, MotionSensor, Speaker, ColorSensor, App, DistanceSensor, Motor, MotorPair
\# 
\# hub = PrimeHub()
`

![CodingRooms Fatal Error](https://user-images.githubusercontent.com/3431967/92248796-3bdc7f00-ee97-11ea-8a7b-be94a9dcf61e.png)

This could have to do with how the program is "streaming" to the brick?  Things to check: long programs, long comments, etc. Double check that all data is making it from browser to brick.  Since we don't "read back" the program from the brick, a potential solution could be: remove all "blank lines" and "comments" (strip out) before sending program to the brick (note: not ideal because modifying user's program, and we might want to add a "read back program" feature in the future).

**Comment by jeremy-jung** [comment]
The problem was indeed with how I handled sending data to the hub, specifically when sending more than twice the block size amount in total. I fixed it. All comments and blank lines should still be getting registered into the hub!

**Comment by edanahy** [comment]
I tested and it seems to be working with long files now.  (Will reopen if someone finds a use-case where it doesn't.)  Closing for now!
