### ISSUE TITLE
Make icon image paths relative (instead of absolute)

### ISSUE THREAD

**Issue by edanahy** [tuftsceeo/Coding-Rooms-for-LEGO-Hardware#27]
Make sure the icon file paths are relative ("./") and not absolute ("/").

E.g.: the Refresh Preview icon

`<button style="position: absolute; background:url('/modules/views/freepik_rotation.png')no-repeat; background-size: 35px 35px; background-position: center; height: 40px; width: 40px;  cursor: pointer; border:none;" id="refresh" class="tooltip">`

should be:

`./modules/views/freepik_rotation.png`

instead.

**Comment by jeremy-jung** [comment]
I made the paths relative!
