### ISSUE TITLE
Link to documentation is absolute ("/") instead of relative ("./")

### ISSUE THREAD

**Issue by edanahy** [tuftsceeo/Coding-Rooms-for-LEGO-Hardware#30]
Similar to #27: the link to the SPIKE Prime documentation is also absolute and should be relative instead:

`documentation.addEventListener("click", function () {
      var url = "/documentation/SPIKE_Prime_Python_Knowledge_Base.htm"
      window.open(url);
})`

**Comment by jeremy-jung** [comment]
Fixed! Thank you.
