### ISSUE TITLE
Order of "play", "reboot", and "stop" buttons

### ISSUE THREAD

**Issue by edanahy** [tuftsceeo/Coding-Rooms-for-LEGO-Hardware#33]
To me, it should be: "Play" and then "Stop" and then (if nothing is working) "reboot"

Currently it is: play, reboot in the middle, and then stop

Thoughts?  Play/Stop are the most used, in that order.

**Comment by jeremy-jung** [comment]
Sounds like a more reasonable layout!

**Comment by edanahy** [comment]
Looks good.  Thanks!
