### ISSUE TITLE
Open Serial issue: "baudRate is undefined"

### ISSUE THREAD

**Issue by edanahy** [tuftsceeo/Coding-Rooms-for-LEGO-Hardware#39]
Chris Rogers (on Mac + Google Chrome with flags enabled) was getting this error.  (He could "see" his brick and select it, and then this error happens.)

![Chris Rogers Connect Error](https://user-images.githubusercontent.com/3431967/93477878-87485180-f8c9-11ea-81f3-ef496aca4bc4.png)

**Comment by jeremy-jung** [comment]
Fixed by Teddy Robbins
