### ISSUE TITLE
Clean up debugging comments

### ISSUE THREAD

**Issue by edanahy** [tuftsceeo/Coding-Rooms-for-LEGO-Hardware#40]
Please go through and cleanup some of the console.log debugging comments.

E.g.
here!
you got cereal

Also: should we add a prefix ("SP:" or "LEGO:" or something) to our debugging comments so we easily know which are caused by our application?

**Comment by jeremy-jung** [comment]
Log messages were cleaned, and new prefixes have been added!

**Comment by edanahy** [comment]
Looks good.  Thanks.
