### ISSUE TITLE
Change windows flag name (new-usb-backend)

### ISSUE THREAD

**Issue by edanahy** [tuftsceeo/Coding-Rooms-for-LEGO-Hardware#41]
The name of the Chrome Browser flag on Windows is "#new-usb-backend" and not "#enable-new-usb-backend":

![codingrooms account 7](https://user-images.githubusercontent.com/3431967/93522731-ed4fcb80-f8ff-11ea-99a5-90d7dcd903ed.jpg)

The browser configuration text needs to be updated.

**Comment by jeremy-jung** [comment]
Fixed!
